# Model arguments
model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: runs/gsm8k/multinode/Qwen2.5-0.5B-Instruct-Gensyn-Swarm

# Dataset
dataset_id_or_path: 'openai/gsm8k'

# Training
max_steps: 20
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03
beta: 0.001
max_prompt_length: 256
max_completion_length: 512  # giảm từ 1024
num_generations: 4          # giảm từ 8
use_vllm: true
vllm_gpu_memory_utilization: 0.1  # giảm từ 0.2

# Logging & Save
logging_strategy: steps
logging_steps: 2
report_to: [tensorboard]
save_strategy: "steps"
save_steps: 25
seed: 42

# Swarm Networking
public_maddr: "/ip4/38.101.215.12/tcp/30002"
host_maddr: "/ip4/0.0.0.0/tcp/38331"
max_rounds: 10000
